<a href="https://colab.research.google.com/github/khalid-bin-Nasir-0/ml_projects/blob/main/ML_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lasso Regression

In [ ]:
import numpy as np

In [ ]:
class lasso():

# initilizing hyperparameter

  def __init__(self,no_of_itteration,learning_rate,lamda):
    self.no_of_itteration=no_of_itteration
    self.learning_rate=learning_rate
    self.lamda = lamda


  def fit(self,x,y):

       self.m,self.n=x.shape
       self.w =np.zeros(self.n)
       self.b = 0
       self.x = x
       self.y = y

# implementing gradient descent algo for optimism
       for i in range(self.no_of_itteration):
        self.update_weight()


  def update_weight(self):

    y_pred = self.predict(self.x)

    # gradiant formula (dw , db)
    for i in range(self.n):
      dw = np.zeros(self.n)

      if self.w[i]>0:

        dw[i] = (-(2*(self.x[:,i]).dot(self.y-y_pred))+self.lamda)/self.m

      else:

         dw[i] = (-(2*(self.x[:,i]).dot(self.y-y_pred))-self.lamda)/self.m

    # db

    db = - 2 * np.sum(self.y-y_pred) / self.m

    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.learning_rate*db



  def predict(self,x):
    return x.dot(self.w)+self.b

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [ ]:
sd = pd.read_csv('/content/salary_data.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/salary_data.csv'

In [ ]:
X = sd.iloc[:,:-1].values
Y= sd.iloc[:,1].values

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=2)

In [ ]:
model = lasso(learning_rate = 0.002 ,no_of_itteration=1000,lamda = 0.005)

In [ ]:
model.fit(x_train,y_train)

In [ ]:
print('weight = ',model.w[0])
print('bias = ',model.b)

In [ ]:
pre_result = model.predict(x_test)

In [ ]:
print(pre_result)

In [ ]:
print(y_test)

# K N N math

**CALCULATING DISTANCE**

Euclidean formula -- rootunder(x2 - x1)^2 + (y2 - y1)^2

In [ ]:
import numpy as np

In [ ]:
# consider two point with 2d
p1 = (1,1)
p2 = (2,2)

In [ ]:
# calculating euclidean dist
dist = (p1[0] - p2[0])**2 + (p1[1]-p2[1])**2
sqroot = np.sqrt(dist)
print(sqroot)

1.4142135623730951

In [ ]:
# consider two point with 3d
p1 = (1,1,1)
p2 = (2,2,2)

In [ ]:
# calculating euclidean dist
dist = (p1[0] - p2[0])**2 + (p1[1]-p2[1])**2 + (p1[2]-p2[2])**2
sqroot = np.sqrt(dist)
print(sqroot)

1.7320508075688772

In [ ]:
# calculating euclidean dist for n no dimension

p1 = (1,1,1,1,1)
p2 = (2,2,2,2,2)
dist = 0
for i in range(len(p1)):
  dist = dist + (p1[i]-p2[i])**2

sqroot = np.sqrt(dist)
print(sqroot)

2.23606797749979

now creating funtion for euclidean distance

In [ ]:
def get_euclidean_funtion(p1,p2):

  dist = 0

  for i in range(len(p1)):
   dist = dist + (p1[i]-p2[i])**2

  sqroot = np.sqrt(dist)
  print(sqroot)

In [ ]:
get_euclidean_funtion((2,2,2,2,2,2),(1,1,1,1,1,1))

2.449489742783178

*Manhattan formula -- |x1-x2| + |y1-y2|*

creating funtion for manhattan dist

In [ ]:
def get_manhattan_funtion(p1,p2):

  dist = 0

  for i in range(len(p1)):
   dist = dist + abs(p1[i]-p2[i])

  print(dist)

In [ ]:
get_manhattan_funtion((1,1,1),(2,2,2))

3

# K N N

In [ ]:
import numpy as np
import statistics

In [ ]:
class knn_classifier():

  def __init__(self , distance_matrix ):

    self.distance_matrix = distance_matrix

# getting the distance metrix
  def get_distance_matrix(self,training_data_point , test_data_point):

    if (self.distance_matrix == 'euclidean'):
      dist = 0
      for i in range(len(training_data_point)-1):
        dist = dist + (training_data_point[i] - test_data_point[i])**2

      eucliudean_distance = np.sqrt(dist)
      return eucliudean_distance


    elif (self.distance_matrix == 'manhattan'):
      dist = 0

      for i in range(len(training_data_point)-1):
        dist = dist + abs(training_data_point[i] - test_data_point[i])

      manhattan_dist = dist
      return manhattan_dist


# getting nearest neighbour
  def nearest_neighbour(self,x_train , test_data , k):

    distance_list = []

    for training_data in x_train:

      distance = self.get_distance_matrix(training_data, test_data)
      distance_list.append((training_data , distance))

    distance_list.sort(key=lambda x:x[1])

    neighbour_list = []

    for j in range(k):
      neighbour_list.append(distance_list[j][0])

      return neighbour_list


  def predict(self, x_train , test_data , k):

    neighbours = self.nearest_neighbour(x_train , test_data , k)

    for data in neighbours:
      label = []
      label.append(data[-1])

    predict_class = statistics.mode(label)

    return predict_class

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
# Data pre-processing

ddf = pd.read_csv('/content/drive/MyDrive/ML dataset/diabetes.csv')

In [ ]:
ddf.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
ddf['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
ddf.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [ ]:
x = ddf.drop(columns= 'Outcome',axis = 1)
y = ddf['Outcome']

In [ ]:
# coverting data type in numpy
x = x.to_numpy()
y = y.to_numpy()

In [ ]:
# train test split
# stratify it does even split data by label mean in this case 50% -- 0 and 50% -- 1 label
x_train , y_train ,x_test , y_test = train_test_split(x,y,test_size = 0.2 , stratify= y , random_state = 2)

In [ ]:
x_train.shape

(614, 8)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(768, 8) (614, 8) (614,)

In [ ]:
print(x_train)

[[0.00e+00 1.19e+02 0.00e+00 ... 3.24e+01 1.41e-01 2.40e+01]
 [6.00e+00 1.05e+02 7.00e+01 ... 3.08e+01 1.22e-01 3.70e+01]
 [1.00e+00 1.89e+02 6.00e+01 ... 3.01e+01 3.98e-01 5.90e+01]
 ...
 [1.10e+01 8.50e+01 7.40e+01 ... 3.01e+01 3.00e-01 3.50e+01]
 [4.00e+00 1.12e+02 7.80e+01 ... 3.94e+01 2.36e-01 3.80e+01]
 [0.00e+00 8.60e+01 6.80e+01 ... 3.58e+01 2.38e-01 2.50e+01]]

In [ ]:
# The previous train_test_split had incorrect variable assignments.
# Re-running it here to ensure x_train and y_train are correctly defined for insertion.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)
x_train = np.insert(x_train , 8 , y_train ,axis = 1)

In [ ]:
x_train.shape

(614, 9)

X_train -- > training data with features and target

X_test -> test data without target

In [ ]:
# MODEL TRAINING :- KNN classifier

classifier = knn_classifier(distance_matrix='euclidean')

NOTE: The KNN CLassifier can predict the label for only one data point at a time

In [ ]:
pred= classifier.predict(x_train ,x_test[68],k=5)
print(pred)

1.0

now for multiple data point

In [ ]:
x_size = x_test.shape

In [ ]:
x_size

(154, 8)

In [ ]:
x_row = x_size[0]

In [ ]:
y_pred = []

for i in range(x_row):
  pred= classifier.predict(x_train ,x_test[i],k=5)
  y_pred.append(pred)

In [ ]:
acc = accuracy_score(y_test , y_pred)
print(acc*100)

67.53246753246754

KNN FROM SKLEARN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
skknn = KNeighborsClassifier(p=2) # p is 2 for euclidien equation

In [ ]:
# The previous train_test_split had incorrect variable assignments.
# Re-running it here to ensure x_train and y_train are correctly defined.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [ ]:
x_train.shape

(614, 8)

In [ ]:
skknn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = skknn.predict(x_test)
acc = accuracy_score(y_test , y_pred)
print(acc*100)

72.72727272727273

# K - Fold cross

In [ ]:
# importing dataset

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [ ]:
# importing models

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
heart_data = pd.read_csv('/content/drive/MyDrive/ML dataset/heart.csv')

In [ ]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
heart_data.shape

(303, 14)

In [ ]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
heart_data.value_counts('target')

target
1    165
0    138
Name: count, dtype: int64

In [ ]:
x = heart_data.drop (columns = 'target',axis = 1)
y = heart_data['target']

In [ ]:
x_train , x_test , y_train,y_test = train_test_split(x,y ,test_size=0.2,stratify = y ,random_state=3)

compairing different model

In [ ]:
# list of models

models = [LogisticRegression(max_iter = 1000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def compare_model_tts():

  for model in models:
    model.fit(x_train,y_train)
    predict = model.predict(x_test)

    acc = accuracy_score(predict,y_test)

    print("the accuracy of model ",model ,"is that ",acc*100)

In [ ]:
compare_model_tts()

the accuracy of model  LogisticRegression(max_iter=1000) is that  78.68852459016394
the accuracy of model  SVC(kernel='linear') is that  77.04918032786885
the accuracy of model  KNeighborsClassifier() is that  65.57377049180327
the accuracy of model  RandomForestClassifier() is that  81.9672131147541

Cross - validation

In [ ]:
# liner regression -- cross val function is alternative of train test split we
# it done all the work for us to split and data according fold which i gave -
# when we use cv = 5 it called stratified kfold method for 5 times where class distribution is even.
lr_cross_val = cross_val_score(LogisticRegression(max_iter=1000),x,y,cv = 5)

print(lr_cross_val*100)

[80.32786885 86.8852459  85.24590164 86.66666667 75.        ]

In [ ]:
mean_acc= sum(lr_cross_val*100)/len(lr_cross_val)

print(mean_acc)

82.82513661202185

In [ ]:
final_mean = round(mean_acc,2)
print(final_mean)

82.83

In [ ]:
# now for svm

svc_val = cross_val_score(SVC(kernel ='linear' ),x,y,cv= 5)

print(svc_val*100)

mean_svc = sum(svc_val*100)/len(svc_val)

print(mean_svc)

[81.96721311 88.52459016 80.32786885 86.66666667 76.66666667]
82.83060109289617

In [ ]:
final_svc = round(mean_svc,2)
print(final_svc)

82.83

In [ ]:
# create funtion to automate these this for training different model with cross val fold

# list of model

models = [LogisticRegression(max_iter = 1000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def acc_of_models(x,y):
  for model in models:
    model_cv_acc = cross_val_score(model,x,y,cv=5)

    model_mean = sum(model_cv_acc*100)/len(model_cv_acc)

    final_acc = round(model_mean, 2)

    print('mean accuracy of ', model ,' on cross val ',final_acc )

In [ ]:
acc_of_models(x,y)

mean accuracy of  LogisticRegression(max_iter=1000)  on cross val  82.83
mean accuracy of  SVC(kernel='linear')  on cross val  82.83
mean accuracy of  KNeighborsClassifier()  on cross val  64.39
mean accuracy of  RandomForestClassifier()  on cross val  82.16

# HYPERPARAMETER

In [ ]:
# importing dependency


import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
# loading the data from sklearn
breast_cancer_dataset = sklearn. datasets. load_breast_cancer()

In [ ]:
print(breast_cancer_dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]), 'frame': None, 'target_names': array(['malignant', 'benign'], dtype='<U9'), 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n', 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23'), 'filename': 'breast_cancer.csv', 'data_module': 'sklearn.datasets.data'}

In [ ]:
bd = pd.DataFrame(breast_cancer_dataset.data,columns = breast_cancer_dataset.feature_names)

In [ ]:
bd['label'] = breast_cancer_dataset.target

In [ ]:
bd.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [ ]:
bd.shape

(569, 31)

In [ ]:
bd.value_counts()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  mean compactness  mean concavity  mean concave points  mean symmetry  mean fractal dimension  radius error  texture error  perimeter error  area error  smoothness error  compactness error  concavity error  concave points error  symmetry error  fractal dimension error  worst radius  worst texture  worst perimeter  worst area  worst smoothness  worst compactness  worst concavity  worst concave points  worst symmetry  worst fractal dimension  label
28.110       18.47         188.50          2499.0     0.11420          0.15160           0.32010         0.159500             0.1648         0.05525                 2.8730        1.4760         21.980           525.600     0.013450          0.027720           0.06389          0.014070              0.04783         0.004476                 28.110        18.47          188.50           2499.0      0.11420           0.15160            0.32010          0.15950               0.1648          0.05525                  0        1
6.981        13.43         43.79           143.5      0.11700          0.07568           0.00000         0.000000             0.1930         0.07818                 0.2241        1.5080         1.553            9.833       0.010190          0.010840           0.00000          0.000000              0.02659         0.004100                 7.930         19.54          50.41            185.2       0.15840           0.12020            0.00000          0.00000               0.2932          0.09382                  1        1
7.691        25.44         48.34           170.4      0.08668          0.11990           0.09252         0.013640             0.2037         0.07751                 0.2196        1.4790         1.445            11.730      0.015470          0.064570           0.09252          0.013640              0.02105         0.007551                 8.678         31.89          54.49            223.6       0.15960           0.30640            0.33930          0.05000               0.2790          0.10660                  1        1
7.729        25.49         47.98           178.8      0.08098          0.04878           0.00000         0.000000             0.1870         0.07285                 0.3777        1.4620         2.492            19.140      0.012660          0.009692           0.00000          0.000000              0.02882         0.006872                 9.077         30.92          57.17            248.0       0.12560           0.08340            0.00000          0.00000               0.3058          0.09938                  1        1
7.760        24.54         47.92           181.0      0.05263          0.04362           0.00000         0.000000             0.1587         0.05884                 0.3857        1.4280         2.548            19.150      0.007189          0.004660           0.00000          0.000000              0.02676         0.002783                 9.456         30.37          59.16            268.6       0.08996           0.06444            0.00000          0.00000               0.2871          0.07039                  1        1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
8.878        15.49         56.74           241.0      0.08293          0.07698           0.04721         0.023810             0.1930         0.06621                 0.5381        1.2000         4.277            30.180      0.010930          0.028990           0.03214          0.015060              0.02837         0.004174                 9.981         17.70          65.27            302.0       0.10150           0.12480            0.09441          0.04762               0.2434          0.07431                  1        1
8.734        16.84         55.27           234.3      0.10390          0.07428           0.00000         0.000000             0.1985         0.07098                 0.5169        2.0790         3.167            28.850      0.015820          0.019660           0.00000          0.000000              0.01865         0.006736                 10.170        22.80          64.01            317.0       0.14600           0.13100            0.00000          0.00000               0.2445          0.08865                  1        1
8.726        15.83         55.84           230.9      0.11500          0.08201           0.04132         0.019240             0.1649         0.07633                 0.1665        0.5864         1.354            8.966       0.008261          0.022130           0.03259          0.010400              0.01708         0.003806                 9.628         19.62          64.48            284.4       0.17240           0.23640            0.24560          0.10500               0.2926          0.10170                  1        1
8.671        14.45         54.42           227.2      0.09138          0.04276           0.00000         0.000000             0.1722         0.06724                 0.2204        0.7873         1.435            11.360      0.009172          0.008007           0.00000          0.000000              0.02711         0.003399                 9.262         17.04          58.36            259.2       0.11620           0.07057            0.00000          0.00000               0.2592          0.07848                  1        1
8.618        11.79         54.34           224.5      0.09752          0.05272           0.02061         0.007799             0.1683         0.07187                 0.1559        0.5796         1.046            8.322       0.010110          0.010550           0.01981          0.005742              0.02090         0.002788                 9.507         15.40          59.90            274.9       0.17330           0.12390            0.11680          0.04419               0.3220          0.09026                  1        1
Name: count, Length: 569, dtype: int64

In [ ]:
bd.value_counts('label')

label
1    357
0    212
Name: count, dtype: int64

In [ ]:
bd.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [ ]:
x = bd.drop(columns='label',axis = 1)
y = bd['label']

In [ ]:
x = np.asarray(x)
y = np.asarray(y)

gridsearch cv

In [ ]:
# loading svc
model = SVC()

In [ ]:
# hyperparameter

parameter = {

        'kernel':['linear','poly','rbf','sigmoid'],
        'C':[1,5,10,20]
}

In [ ]:
# grid search cv

classifier = GridSearchCV(model , parameter, cv = 5)

In [ ]:
# now fit data to model by GridSearchCV with the crossfold  = 5 , it do 1st take model and 1st parameter like linera and
# then 1st from second parameter like = 1 , then 1st fold and train model and then 2nd fold and then after all 5 fold it change 2nd parameter and find the accuracy like that for all the parameter combination

classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([1.39038010e+00, 3.86095047e-03, 4.64386940e-03, 1.46104336e-02,
        3.32249436e+00, 4.09193039e-03, 4.66899872e-03, 1.44017696e-02,
        5.17066045e+00, 4.31151390e-03, 4.17609215e-03, 1.44704342e-02,
        8.56430717e+00, 4.58750725e-03, 6.21399879e-03, 1.40855789e-02]),
 'std_fit_time': array([5.60968992e-01, 1.64286352e-04, 1.57909101e-04, 3.48626685e-04,
        1.09448128e+00, 2.85311257e-04, 6.21756040e-04, 1.28938666e-03,
        1.34198512e+00, 1.42851165e-04, 7.94230082e-05, 1.11733818e-03,
        2.98520406e+00, 2.74763592e-04, 1.15081632e-03, 7.49928916e-04]),
 'mean_score_time': array([0.00128322, 0.00139399, 0.00201855, 0.00397439, 0.00131125,
        0.00143948, 0.00191851, 0.00425582, 0.00132256, 0.00138049,
        0.0018002 , 0.00373874, 0.0014286 , 0.00138326, 0.00253048,
        0.00375032]),
 'std_score_time': array([5.84796403e-05, 3.94262158e-05, 1.02527818e-04, 1.34033607e-04,
        1.90288940e-04, 6.34477666e-05, 1.09855603e-04, 9.11697052e-04,
        2.56400506e-04, 6.92158988e-05, 1.01466040e-04, 2.52362731e-04,
        3.55252291e-04, 5.43860738e-05, 5.73556309e-04, 2.85541103e-04]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.94736842, 0.84210526, 0.85087719, 0.54385965, 0.94736842,
        0.88596491, 0.88596491, 0.49122807, 0.93859649, 0.88596491,
        0.87719298, 0.48245614, 0.92982456, 0.87719298, 0.87719298,
        0.47368421]),
 'split1_test_score': array([0.92982456, 0.88596491, 0.89473684, 0.45614035, 0.93859649,
        0.9122807 , 0.92982456, 0.42105263, 0.93859649, 0.92105263,
        0.92105263, 0.40350877, 0.95614035, 0.92105263, 0.92105263,
        0.40350877]),
 'split2_test_score': array([0.97368421, 0.92982456, 0.92982456, 0.46491228, 0.97368421,
        0.92105263, 0.93859649, 0.42105263, 0.97368421, 0.90350877,
        0.9122807 , 0.42105263, 0.95614035, 0.90350877, 0.92105263,
        0.42105263]),
 'split3_test_score': array([0.92105263, 0.94736842, 0.94736842, 0.38596491, 0.92982456,
        0.93859649, 0.94736842, 0.35087719, 0.94736842, 0.93859649,
        0.95614035, 0.34210526, 0.93859649, 0.93859649, 0.94736842,
        0.34210526]),
 'split4_test_score': array([0.95575221, 0.9380531 , 0.9380531 , 0.45132743, 0.96460177,
        0.95575221, 0.95575221, 0.37168142, 0.96460177, 0.95575221,
        0.94690265, 0.36283186, 0.96460177, 0.95575221, 0.9380531 ,
        0.3539823 ]),
 'mean_test_score': array([0.94553641, 0.90866325, 0.91217202, 0.46044093, 0.95081509,
        0.92272939, 0.93150132, 0.41117839, 0.95256948, 0.920975  ,
        0.92271386, 0.40239093, 0.9490607 , 0.91922062, 0.92094395,
        0.39886664]),
 'std_test_score': array([0.01868869, 0.03938232, 0.03544367, 0.05025317, 0.01621632,
        0.02368918, 0.02435811, 0.04857818, 0.01419963, 0.02470123,
        0.02787898, 0.0489065 , 0.01281637, 0.02730027, 0.02410455,
        0.0476401 ]),
 'rank_test_score': array([ 4, 12, 11, 13,  2,  6,  5, 14,  1,  8,  7, 15,  3, 10,  9, 16],
       dtype=int32)}

In [ ]:
# check the best paramerter
best_parameter = classifier.best_params_
print(best_parameter)

{'C': 10, 'kernel': 'linear'}

In [ ]:
# check the what is highest accuracy of best parameter
highest_acc = classifier.best_score_
print(highest_acc)

0.9525694767893185

In [ ]:
# create data frame of result

result_df = pd.DataFrame(classifier.cv_results_)

In [ ]:
result_df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.390380,0.560969,0.001283,0.000058,1,linear,"{'C': 1, 'kernel': 'linear'}",0.947368,0.929825,0.973684,0.921053,0.955752,0.945536,0.018689,4
1,0.003861,0.000164,0.001394,0.000039,1,poly,"{'C': 1, 'kernel': 'poly'}",0.842105,0.885965,0.929825,0.947368,0.938053,0.908663,0.039382,12
2,0.004644,0.000158,0.002019,0.000103,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.850877,0.894737,0.929825,0.947368,0.938053,0.912172,0.035444,11
3,0.014610,0.000349,0.003974,0.000134,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.543860,0.456140,0.464912,0.385965,0.451327,0.460441,0.050253,13
4,3.322494,1.094481,0.001311,0.000190,5,linear,"{'C': 5, 'kernel': 'linear'}",0.947368,0.938596,0.973684,0.929825,0.964602,0.950815,0.016216,2

In [ ]:
# make df for only mean_test_score
grid_search_result = result_df[['param_C','param_kernel','mean_test_score']]
grid_search_result

    param_C param_kernel  mean_test_score
0         1       linear         0.945536
1         1         poly         0.908663
2         1          rbf         0.912172
3         1      sigmoid         0.460441
4         5       linear         0.950815
5         5         poly         0.922729
6         5          rbf         0.931501
7         5      sigmoid         0.411178
8        10       linear         0.952569
9        10         poly         0.920975
10       10          rbf         0.922714
11       10      sigmoid         0.402391
12       20       linear         0.949061
13       20         poly         0.919221
14       20          rbf         0.920944
15       20      sigmoid         0.398867

Randomized search cv

In [ ]:
# loading svc
model = SVC()

In [ ]:
# randomized search cv

Rclassifier = RandomizedSearchCV(model , parameter, cv = 5)

In [ ]:
Rclassifier.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [ ]:
# result of randomclassifier
Rclassifier.cv_results_

{'mean_fit_time': array([0.06976261, 0.01679969, 0.05673137, 0.01163316, 0.00753088,
        6.29701996, 0.00647521, 0.02224751, 0.00761547, 0.00662475]),
 'std_fit_time': array([2.33396638e-02, 3.32906937e-03, 4.60450981e-03, 4.77718890e-03,
        9.30799988e-04, 3.19742366e+00, 9.00924649e-04, 3.12553632e-03,
        9.74726705e-04, 3.04872295e-04]),
 'mean_score_time': array([0.01956   , 0.00632038, 0.01603069, 0.00538621, 0.00387015,
        0.00146914, 0.00216732, 0.00587358, 0.00251088, 0.00297246]),
 'std_score_time': array([0.01002705, 0.00180927, 0.00236899, 0.00377882, 0.00130033,
        0.00022035, 0.00010032, 0.00073637, 0.00036138, 0.0001046 ]),
 'param_kernel': masked_array(data=['sigmoid', 'rbf', 'sigmoid', 'rbf', 'rbf', 'linear',
                    'poly', 'sigmoid', 'poly', 'rbf'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[1, 20, 5, 1, 10, 10, 5, 10, 10, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'kernel': 'sigmoid', 'C': 1},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'sigmoid', 'C': 5},
  {'kernel': 'rbf', 'C': 1},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'poly', 'C': 5},
  {'kernel': 'sigmoid', 'C': 10},
  {'kernel': 'poly', 'C': 10},
  {'kernel': 'rbf', 'C': 5}],
 'split0_test_score': array([0.54385965, 0.87719298, 0.49122807, 0.85087719, 0.87719298,
        0.93859649, 0.88596491, 0.48245614, 0.88596491, 0.88596491]),
 'split1_test_score': array([0.45614035, 0.92105263, 0.42105263, 0.89473684, 0.92105263,
        0.93859649, 0.9122807 , 0.40350877, 0.92105263, 0.92982456]),
 'split2_test_score': array([0.46491228, 0.92105263, 0.42105263, 0.92982456, 0.9122807 ,
        0.97368421, 0.92105263, 0.42105263, 0.90350877, 0.93859649]),
 'split3_test_score': array([0.38596491, 0.94736842, 0.35087719, 0.94736842, 0.95614035,
        0.94736842, 0.93859649, 0.34210526, 0.93859649, 0.94736842]),
 'split4_test_score': array([0.45132743, 0.9380531 , 0.37168142, 0.9380531 , 0.94690265,
        0.96460177, 0.95575221, 0.36283186, 0.95575221, 0.95575221]),
 'mean_test_score': array([0.46044093, 0.92094395, 0.41117839, 0.91217202, 0.92271386,
        0.95256948, 0.92272939, 0.40239093, 0.920975  , 0.93150132]),
 'std_test_score': array([0.05025317, 0.02410455, 0.04857818, 0.03544367, 0.02787898,
        0.01419963, 0.02368918, 0.0489065 , 0.02470123, 0.02435811]),
 'rank_test_score': array([ 8,  6,  9,  7,  4,  1,  3, 10,  5,  2], dtype=int32)}

In [ ]:
# check the best paramerter
R_best_parameter = Rclassifier.best_params_
print(best_parameter)

{'C': 10, 'kernel': 'linear'}

In [ ]:
# check the what is highest accuracy of best parameter
Rhighest_acc = Rclassifier.best_score_
print(Rhighest_acc)

0.9525694767893185

In [ ]:
# create data frame of result

result_df = pd.DataFrame(Rclassifier.cv_results_)

In [ ]:
result_df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.069763,0.023340,0.019560,0.010027,sigmoid,1,"{'kernel': 'sigmoid', 'C': 1}",0.543860,0.456140,0.464912,0.385965,0.451327,0.460441,0.050253,8
1,0.016800,0.003329,0.006320,0.001809,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.877193,0.921053,0.921053,0.947368,0.938053,0.920944,0.024105,6
2,0.056731,0.004605,0.016031,0.002369,sigmoid,5,"{'kernel': 'sigmoid', 'C': 5}",0.491228,0.421053,0.421053,0.350877,0.371681,0.411178,0.048578,9
3,0.011633,0.004777,0.005386,0.003779,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.850877,0.894737,0.929825,0.947368,0.938053,0.912172,0.035444,7
4,0.007531,0.000931,0.003870,0.001300,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.877193,0.921053,0.912281,0.956140,0.946903,0.922714,0.027879,4

In [ ]:
# make df for only mean_test_score
grid_search_result = result_df[['param_C','param_kernel','mean_test_score']]
grid_search_result

   param_C param_kernel  mean_test_score
0        1      sigmoid         0.460441
1       20          rbf         0.920944
2        5      sigmoid         0.411178
3        1          rbf         0.912172
4       10          rbf         0.922714
5       10       linear         0.952569
6        5         poly         0.922729
7       10      sigmoid         0.402391
8       10         poly         0.920975
9        5          rbf         0.931501

In [ ]:
# after this we conclude and get the best hyperparameter values with highest accuracy so then --- we split our data into train test split
# and then select model which we want and use their parameter like -- SVC(-- here we place the that parameter and train our model)

# MODEL Selection

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [ ]:
# importing the models
from sklearn. linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# loading data

heart_df = pd.read_csv("/content/drive/MyDrive/ML dataset/heart.csv")

In [ ]:
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
heart_df.shape

(303, 14)

In [ ]:
heart_df.value_counts('target')

target
1    165
0    138
Name: count, dtype: int64

In [ ]:
# seprating target and feature
x= heart_df.drop(columns = 'target',axis = 1 )
y = heart_df['target']

In [ ]:
print(x)
print(y)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
x = np.asarray(x)
y = np.asarray(y)

model section

In [ ]:
# comparing the model with deafult paramerter value..................

In [ ]:
# list of model
models = [LogisticRegression(max_iter=1000),SVC(kernel= 'linear'),KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

In [ ]:
def compare_models_crros_val_score():

  for model in models:
   cv_score = cross_val_score(model , x ,y ,cv = 5)
   mean_score = sum(cv_score)/len(cv_score)*100
   mean_acc = round(mean_score,2)


   print('the accuracy of model on folds',model,'is that',cv_score)
   print('the mean accuracy of model',model,'is that',mean_acc)

In [ ]:
compare_models_crros_val_score()

the accuracy of model on folds LogisticRegression(max_iter=1000) is that [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
the mean accuracy of model LogisticRegression(max_iter=1000) is that 82.83
the accuracy of model on folds SVC(kernel='linear') is that [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
the mean accuracy of model SVC(kernel='linear') is that 82.83
the accuracy of model on folds KNeighborsClassifier() is that [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
the mean accuracy of model KNeighborsClassifier() is that 64.39
the accuracy of model on folds RandomForestClassifier(random_state=0) is that [0.85245902 0.90163934 0.81967213 0.81666667 0.8       ]
the mean accuracy of model RandomForestClassifier(random_state=0) is that 83.81

In [ ]:
# we compare model with different hyperparameter value ..............

In [ ]:
# list of model
models = [LogisticRegression(max_iter=10000),SVC(),KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

In [ ]:
# creating dictionary that contain hyperparameter value

parameter = {

             'logistic_regression':{

                'C':[1,5,10,20]
             },

             'svc':{
                 'kernel':['linear','poly','rbf','sigmoid'],
                 'C':[1,5,10,20]

             },

             'KNN':{
                 'n_neighbors':[3,5,10]
             },

             'random_forest':{

                   'n_estimators':[10,20,50,100]
             }



}

In [ ]:
print(parameter['logistic_regression'])

{'C': [1, 5, 10, 20]}

In [ ]:
model_key = list(parameter.keys())

In [ ]:
print(model_key)

['logistic_regression', 'svc', 'KNN', 'random_forest']

In [ ]:
model_key[0]

'logistic_regression'

In [ ]:
print(parameter[model_key[0]])

{'C': [1, 5, 10, 20]}

In [ ]:
def comapare_model_hyper(li_model,hyperparameter_dict):

  result = []
  i= 0
  for model in li_model:
    key = model_key[i]
    param= hyperparameter_dict[key]
    i+=1

    print(model,'.....')
    print(param)
#    now give the value to GridSearchCV for training
    classifier = GridSearchCV(model,param,cv=5)
    # now fit the clssifier
    classifier.fit(x,y)

    result.append({

              'model used':model,
              'highest_score':classifier.best_score_,
              'best parameter': classifier.best_params_
    })

  result_df = pd.DataFrame(result,columns=['model used','highest_score','best parameter'])

  return result_df

In [ ]:
comapare_model_hyper(models,parameter)

LogisticRegression(max_iter=10000) .....
{'C': [1, 5, 10, 20]}
SVC() .....
{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}
KNeighborsClassifier() .....
{'n_neighbors': [3, 5, 10]}
RandomForestClassifier(random_state=0) .....
{'n_estimators': [10, 20, 50, 100]}

,model used,highest_score,best parameter
0,LogisticRegression(max_iter=10000),0.831585,{'C': 5}
1,SVC(),0.828306,"{'C': 1, 'kernel': 'linear'}"
2,KNeighborsClassifier(),0.643880,{'n_neighbors': 5}
3,RandomForestClassifier(random_state=0),0.838087,{'n_estimators': 100}

In [ ]:
# now we split the data into training and test data and use model which have highest accuracy with their best parameter
# and train model

this is model selection process