<a href="https://colab.research.google.com/github/khalid-bin-Nasir-0/ml_projects/blob/main/ML_pro2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam mail pred

importing dependencies

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data collection

In [ ]:
mail_data = pd.read_csv("/content/drive/MyDrive/ML dataset/mail_data.csv")

In [ ]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
mail_data.shape

(5572, 2)

label encoding -- category spam - 0, ham - 1

In [ ]:
mail_data.loc[mail_data['Category'] == 'spam','Category',]=0
mail_data.loc[mail_data['Category'] == 'ham','Category',]=1

In [ ]:
mail_data.head()

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

In [ ]:
x = mail_data['Message']

In [ ]:
y = mail_data['Category']

In [ ]:
print(y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

spliting data into training and test daat

In [ ]:
x_train , x_test , y_train,y_test = train_test_split(x,y,test_size=0.2 , random_state=2)

In [ ]:
# transform the text data to feature vectors that can be used as input to logistic regression model
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

x_train = feature_extraction.fit_transform(x_train)
x_test= feature_extraction.transform(x_test)

print(x_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34768 stored elements and shape (4457, 7458)>
  Coords	Values
  (0, 6927)	0.48935591439341625
  (0, 6586)	0.44333254982109394
  (0, 3958)	0.6161071828926097
  (0, 4334)	0.42941702167641554
  (1, 3168)	0.5869421390016224
  (1, 6971)	0.4281243465155688
  (1, 1428)	0.5869421390016224
  (1, 2121)	0.35736171430221464
  (2, 6878)	0.35749230587184955
  (2, 1876)	0.28751725124107325
  (2, 5894)	0.35749230587184955
  (2, 806)	0.26730249393705324
  (2, 5695)	0.35749230587184955
  (2, 4884)	0.35749230587184955
  (2, 3852)	0.3408491178137899
  (2, 7353)	0.31988118061968496
  (2, 5115)	0.3408491178137899
  (3, 1876)	0.3080768784015236
  (3, 7297)	0.22192369472149484
  (3, 7000)	0.30072945056088285
  (3, 7065)	0.32795623716393424
  (3, 2060)	0.24915048132454623
  (3, 5005)	0.3169028431039865
  (3, 7248)	0.23571908490908416
  (3, 300)	0.2915969875465198
  :	:
  (4454, 4627)	0.3831814754124698
  (4454, 311)	0.19547195974237946
  (4454, 5068)	0.22284357632450164
  (4454, 1094)	0.24862733340971144
  (4454, 1575)	0.20946314330145205
  (4454, 666)	0.28653660324238944
  (4454, 2244)	0.2526916142542512
  (4454, 7084)	0.2689097965804433
  (4454, 571)	0.3005277868014621
  (4454, 5077)	0.3005277868014621
  (4454, 297)	0.3005277868014621
  (4455, 3084)	0.3019392955127119
  (4455, 4614)	0.4677148905542796
  (4455, 3701)	0.546620099025937
  (4455, 7075)	0.6255253074975946
  (4456, 6575)	0.15362974460832007
  (4456, 5820)	0.18767970267638426
  (4456, 7376)	0.20404881687716278
  (4456, 7033)	0.43304344994724825
  (4456, 380)	0.24893867331233713
  (4456, 2509)	0.20620887737471993
  (4456, 7032)	0.2868954144677231
  (4456, 909)	0.26924653489772427
  (4456, 5009)	0.6018082365591317
  (4456, 3768)	0.30090411827956587

In [ ]:
# convert y_train and y_test value as integers

y_train = y_train.astype('int')
y_test = y_test.astype('int')


print(y_train)

3890    1
5553    1
4366    1
3968    0
3771    1
       ..
3335    1
1099    1
2514    0
3606    1
2575    0
Name: Category, Length: 4457, dtype: int64

training the model

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
train_pred = model.predict(x_train)

In [ ]:
accuracy = accuracy_score(y_train,train_pred)

In [ ]:
print(accuracy)

0.9685887368184878

In [ ]:
test_pred = model.predict(x_test)
accuracy = accuracy_score(y_test,test_pred)
print(accuracy)

0.9533632286995516